name: C++ CI Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install g++
    
    - name: Build with g++
      run: g++ -pthread main.cpp -o task_system

    - name: Run the Task System
      run: |
        echo "Running the task system"
        ./task_system <<EOF
        3
        Deploy Server
        0
        Compile Report
        1
        Send Email
        2
        EOF
